var json_Waypoints_21ENE19waypoints_0 = {
"type": "FeatureCollection",
"name": "Waypoints_21ENE19waypoints_0",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "ele": 63.286, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "168", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.803072, -30.322041 ] } },
{ "type": "Feature", "properties": { "ele": 57.549, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "169", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.803502, -30.321281 ] } },
{ "type": "Feature", "properties": { "ele": 57.874, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "170", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.802764, -30.321527 ] } },
{ "type": "Feature", "properties": { "ele": 61.779, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "171", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.801822, -30.322218 ] } },
{ "type": "Feature", "properties": { "ele": 53.781, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "172", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.802089, -30.321341 ] } },
{ "type": "Feature", "properties": { "ele": 53.792, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "173", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.802427, -30.320673 ] } },
{ "type": "Feature", "properties": { "ele": 51.139, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "174", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.801057, -30.32169 ] } },
{ "type": "Feature", "properties": { "ele": 41.717, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "175", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.801796, -30.320147 ] } },
{ "type": "Feature", "properties": { "ele": 62.249, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "176", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.801778, -30.319997 ] } },
{ "type": "Feature", "properties": { "ele": 62.923, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "177", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.804274, -30.31776 ] } },
{ "type": "Feature", "properties": { "ele": 67.714, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "178", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.805442, -30.316567 ] } },
{ "type": "Feature", "properties": { "ele": 55.623, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "179", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.806139, -30.316018 ] } },
{ "type": "Feature", "properties": { "ele": 71.643, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "180", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.808371, -30.317606 ] } },
{ "type": "Feature", "properties": { "ele": 63.751, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "181", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.806572, -30.31797 ] } },
{ "type": "Feature", "properties": { "ele": 63.987, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "182", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.80679, -30.319046 ] } },
{ "type": "Feature", "properties": { "ele": 66.445, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "183", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.804933, -30.319946 ] } },
{ "type": "Feature", "properties": { "ele": 55.219, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "184", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.804173, -30.321296 ] } },
{ "type": "Feature", "properties": { "ele": 59.004, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "185", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.805061, -30.321638 ] } },
{ "type": "Feature", "properties": { "ele": 66.198, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "186", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.804553, -30.321845 ] } },
{ "type": "Feature", "properties": { "ele": 47.763, "time": "2019-01-21T00:00:00.000", "magvar": null, "geoidheight": null, "name": "187", "cmt": null, "desc": "Waypoint", "src": null, "link1_href": null, "link1_text": null, "link1_type": null, "link2_href": null, "link2_text": null, "link2_type": null, "sym": "Flag, Blue", "type": null, "fix": null, "sat": null, "hdop": null, "vdop": null, "pdop": null, "ageofdgpsdata": null, "dgpsid": null }, "geometry": { "type": "Point", "coordinates": [ -57.80303, -30.322888 ] } }
]
}
